/**
 * @file tal_irq_handler.c
 *
 * @brief This file handles the interrupts generated by the transceiver.
 *
 * $Id: tal_irq_handler.c,v 1.2 2010-07-31 07:04:16 slb Exp $
 *
 * @author    Atmel Corporation: http://www.atmel.com
 * @author    Support email: avr@atmel.com
 */
/*
 * Copyright (c) 2009, Atmel Corporation All rights reserved.
 *
 * Licensed under Atmel's Limited License Agreement --> EULA.txt
 */

#include "../../../../ubiconfig.h"

#if (ATMEGARF_TAL_1 == TAL_TYPE)

/* === INCLUDES ============================================================ */

#include <stdint.h>
#include <stdbool.h>
#include <stddef.h>
#include "../../../PAL/Inc/pal.h"
#include "../../../Include/return_val.h"
#include "../../Inc/tal.h"
#include "../../../Include/ieee_const.h"
#include "../../../Include/stack_config.h"
#include "../../../Resources/Buffer_Management/Inc/bmm.h"
#include "../../../Resources/Queue_Management/Inc/qmm.h"
#include "../Inc/tal_irq_handler.h"
#include "../Inc/tal_rx.h"
#include "../Inc/atmega128rfa1.h"
#include "../../../Include/_tal_internal.h"
#include "../../../Include/_tal_constants.h"
#include "../Inc/tal_tx.h"
#include "../../../Include/mac_build_config.h"

/* === TYPES =============================================================== */


/* === MACROS ============================================================== */


/* === GLOBALS ============================================================= */


/* === PROTOTYPES ========================================================== */


/* === IMPLEMENTATION ====================================================== */

/**
 * @brief Transceiver interrupt handler
 *
 * This function handles the transceiver generated interrupts.
 */
void trx_rx_end_handler_cb(void)
{
    ENTER_CRITICAL_REGION();

    /* Handle rx interrupt. */
    handle_received_frame_irq();    // see tal_rx.c

    LEAVE_CRITICAL_REGION();
}/* trx_rx_end_handler_cb() */

void trx_tx_end_handler_cb(void)
{
    ENTER_CRITICAL_REGION();

    /* Get the result and push it to the queue. */
    handle_tx_end_irq();            // see tal_tx.c

    LEAVE_CRITICAL_REGION();
}/* trx_irq_handler_cb() */


/**
 * @brief Timestamp interrupt handler
 *
 * This function handles the interrupts handling the timestamp.
 */
void trx_irq_timestamp_handler_cb(void)
{
    pal_trx_read_timestamp(&tal_rx_timestamp);
}

#endif /* (ATMEGARF_TAL_1 == TAL_TYPE) */

/* EOF */
